# -*- coding: utf-8 -*-

from setuptools import setup, find_packages


CLASSIFIERS = ['Environment :: Web Environment',
'Framework :: Django',
'Intended Audience :: Science/Research',
'Intended Audience :: Education',
'Programming Language :: Python',
'Programming Language :: JavaScript',
'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
'Topic :: Internet :: WWW/HTTP :: WSGI :: Application',
'Topic :: Multimedia :: Sound/Audio',
'Topic :: Multimedia :: Sound/Audio :: Analysis',
'Topic :: Multimedia :: Sound/Audio :: Players',
'Topic :: Scientific/Engineering :: Information Analysis',
'Topic :: System :: Archiving',  ]


setup(
  name = "Francoralite",
  url = "http://francoralite.org",
  description = "Open web audio application with semantics",
  long_description = open('README.md').read(),
  author = "Luc Leger",
  author_email = "leger.luc@gmail.com",
  version = '1.7.0',
  install_requires = [
    'django==4.2.13',
    'django-appconf==1.0.6',
    'django-filter==24.2',
    'djangorestframework==3.15.1',
    'djangorestframework-xml==2.0.0',
    'drf-nested-routers==0.94.1',
    'drf-yasg==1.21.7',
    'gunicorn==22.0.0',
    'psycopg2-binary==2.9.9',
    'pyaml==20.4.0',
    'mysqlclient==2.2.4',
    'django-registration-redux==2.13',
    'django-extensions==3.2.3',
    'django-debug-toolbar==4.3.0',
    'django-extra-views==0.14.0',
    'pyyaml==6.0.1',
    'Werkzeug==3.0.3',
    'django-dirtyfields==1.9.2',
    'sqlparse==0.5.0',
    'django-markdownx==4.0.7',
    'django_select2==8.1.2',
    'lxml==5.2.2',
    'django-leaflet==0.30.0',
    'django-geojson==4.1.0',
    'django-cors-headers==4.3.1',
    'python-keycloak==4.0.0',
    'rsa==4.9',
    'python-jose==3.3.0',
    'mozilla-django-oidc==4.0.1',
    'rdflib==7.0.0',
  ],
  extras_require={
    'tests': [
      'factory_boy==3.3.0',
      'ipython==8.24.0',
      'parameterized==0.9.0',
      'pytest==8.2.1',
      'pytest-cov==5.0.0',
      'pytest-django==4.8.0',
      'pytest-env==1.1.3',
      'pytest-selenium==4.1.0',
      'coveralls==4.0.1',
      'selenium==4.21.0',
      'coverage==7.5.1',
      'coveragepy-lcov==0.1.2',
      'icecream==2.1.3',
      'tenacity>=8.2.3,<8.4.0',
    ],
  },
  platforms = ['OS Independent'],
  license = 'CeCILL v2',
  classifiers = CLASSIFIERS,
  packages = find_packages(),
  include_package_data = True,
  zip_safe = False,
)
